version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    assignees:
      - aliyome
    reviewers:
      - aliyome
